service: serverless-fastapi
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements